spring:
  datasource:
    mysqldb:
      url: jdbc:mysql://localhost:3306/mysqldb
      username: root
      password: password
    psqldb:
      url: jdbc:postgresql://localhost:5432/psqldb
      username: postgres
      password: 
  data:
    mongodb:
      uri: mongodb://localhost:27017/mongodb
  mail:
    host: smtp.gmail.com
    port: 587
    username: from@gmail.com
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
